routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

//about
Route::get('/about', 'AboutController@index');

//Product
Route::get('/productCategories', 'ProductCategoryController@index');
Route::get('/productCategories/{id}', 'ProductCategoryController@show');
Route::get('/product/{id}', 'ProductController@index');
Route::get('/products/search', 'ProductCategoryController@search')->name('product.search');
Route::get('/products/specifications/search', 'ProductCategoryController@searchSpecifications')->name('product.specification.search');

//Info
Route::get('/infoCategories', 'InfoCategoryController@index');
Route::get('/infoCategories/{id}', 'InfoCategoryController@show');
Route::get('/info/{id}', 'InfoController@index');

//News
Route::get('/newsCategories', 'NewsCategoryController@index');
Route::get('/newsCategories/{id}', 'NewsCategoryController@show');
Route::get('/news/{id}', 'NewsController@index');

//Contact
Route::get('/contact', 'ContactController@index');

//Send Mail
Route::get('/sendemail', 'ContactController@send');

//inquiry car
Route::get('/inquiry_car', 'ContactController@inquiry');

//Send Mail
Route::get('/inquiry_send', 'ContactController@inquiry_send');
/*
Route::get('/', function () {
    return view('layouts.default');
});
*/

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () {

    Route::get('/', 'ProductsController@index')->name('home');
    Route::get('/home', 'ProductsController@index')->name('home.index');

    //Route::get('/news/categories', 'NewsCategoriesController@index')->name('admin.news.category.index');
    Route::resource('/news/categories', 'NewsCategoriesController', [
        'as' => 'news'
    ]);
    Route::resource('/news', 'NewsController');
    Route::resource('/info/categories', 'InfoCategoriesController', [
        'as' => 'info'
    ]);
    Route::resource('/info', 'InfoController');
    Route::resource('/banner/categories', 'BannersCategoriesController', [
        'as' => 'banner'
    ]);
    Route::resource('/banners', 'BannersController');
    Route::resource('/sub/banners', 'SubBannersController', [
        'as' => 'sub'
    ]);
    Route::resource('/product/categories', 'ProductCategoriesController', [
        'as' => 'product'
    ]);
    Route::resource('/product/specification/categories', 'SpecificationCategoriesController', [
        'as' => 'product.specification'
    ]);
    
    Route::get('/product/specifications/list', 'SpecificationsController@list')->name('product.specifications.list');
    Route::resource('/product/specifications', 'SpecificationsController', [
        'as' => 'product'
    ]);

    Route::get('/product/specifications_by_category/{id}', 'SpecificationsController@specificationsByCategoryID');

    Route::resource('/product/specification/items', 'SpecificationItemsController', [
        'as' => 'product.specification'
    ]);
    Route::resource('/products', 'ProductsController');
    Route::get('/products/{id}/copy', 'ProductsController@copy')->name('products.copy');

    Route::get('/about', 'PagesController@index')->name('page.index');
    Route::put('/about/{id}', 'PagesController@update')->name('page.update');
    Route::post('/about', 'PagesController@store')->name('page.store');

    Route::post('/upload/images', 'ImagesController@upload');
    Route::post('/upload/images/delete', 'ImagesController@destroy');
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('/admin/laravel-filemanager', '\UniSharp\LaravelFilemanager\Controllers\LfmController@show');
    Route::post('/admin/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\Controllers\UploadController@upload');
    // list all lfm routes here...
});

Auth::routes();

app/Models/Info.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Info extends Model
{
    protected $fillable = ['title', 'excerpt', 'seo_keyword', 'content', 'status', 'category_id', 'sort', 'post_date'];

    public function scopePublish($query)
    {
        return $query->where('status', 1);
    }

    public function category()
    {
        return $this->belongsTo('App\Models\InfoCategory', 'category_id', 'id');
    }

}

app/Http/Controllers/Admin/InfoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Repositories\InfoCategoryRepository;
use App\Repositories\InfoRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Validator;
use PhpParser\Node\Expr\Array_;

class infoController extends Controller
{
    protected $repository;
    protected $category;

    public function __construct(InfoRepository $repository, InfoCategoryRepository $category)
    {
        $this->middleware('auth');
        $this->repository = $repository;
        $this->category = $category;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $infos = $this->repository->infoListWithCategory();

        //dd($infoList);
        return view('admin.info.index', compact('infos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = $this->category->infoCategories();

        return view('admin.info.create_edit', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request->all());
        $validator = Validator::make($request->all(),[
            'title' => 'required',
            'content' => 'required',
            'category_id' => 'required',
        ]);

        if ($validator->fails()) {
            $messages = $validator->messages();
            //dd($messages);
            return Redirect::back()
                ->withErrors($validator)
                ->withInput();
        }

        //dd($request->all());
        $data = array();
        $data['title'] = $request->get('title');
        $excerpt = $request->get('excerpt');
        if (isset($excerpt)) {
            $data['excerpt'] = $excerpt;
        }
        $seo_keyword = $request->get('seo_keyword');
        if (isset($seo_keyword)) {
            $data['seo_keyword'] = $seo_keyword;
        }
        $data['content'] = htmlentities($request->get('content'), ENT_COMPAT , "UTF-8");
        $data['category_id'] = $request->get('category_id');
        $data['status'] = $request->get('my-checkbox') === 'on'?1:0;
        $data['sort'] = $request->get('sort');
        $data['post_date'] = $request->get('post_date');

        $this->repository->create($data);

        return redirect()->route('admin.info.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $info = $this->repository->infoWithCategory($id);

        //dd($info);
        return view('admin.info.show', compact('info'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $info = $this->repository->infoWithCategory($id);
        $categories = $this->category->infoCategories();
        //dd($info);
        return view('admin.info.create_edit', compact('info', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //dd($id);
        $validator = Validator::make($request->all(),[
            'title' => 'required',
            'content' => 'required',
            'category_id' => 'required',
        ]);

        if ($validator->fails()) {
            $messages = $validator->messages();
            //dd($messages);
            return Redirect::back()
                ->withErrors($validator)
                ->withInput();
        }

        //dd($request->all());
        $info = $this->repository->info($id);
        //dd($info);
        $info->title = $request->get('title');
        $excerpt = $request->get('excerpt');
        if (isset($excerpt)) {
            $info->excerpt = $excerpt;
        }
        $seo_keyword = $request->get('seo_keyword');
        if (isset($seo_keyword)) {
            $info['seo_keyword'] = $seo_keyword;
        }
        $info->content = htmlentities($request->get('content'), ENT_COMPAT , "UTF-8");
        $info->category_id = $request->get('category_id');
        $info->status = $request->get('my-checkbox') === 'on'?1:0;
        $info->sort = $request->get('sort');
        $info->post_date = $request->get('post_date');

        $info->save();

        return redirect()->route('admin.info.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //dd('delete:'.$id);
        $this->repository->delete($id);

        return redirect()->route('admin.info.index');
    }
}

app/Http/Controllers/InfoController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\InfoRepository;
use App\Repositories\InfoCategoryRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Config;

class InfoController extends Controller
{
	protected $repository;
    protected $categoryRepository;

    public function __construct(InfoRepository $repository, InfoCategoryRepository $categoryRepository)
    {
        $this->repository = $repository;
        $this->categoryRepository = $categoryRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($id)
    {
        $info = $this->repository->info($id);
        $infoCategory = $this->categoryRepository->infoCategory($info->category_id);
//dd($infoCategory);
        $page_title = $info->title;
        $page_keyword = null;
        if (isset($info->seo_keyword)) {
            $page_keyword = $info->seo_keyword;
        }
        $page_description = null;
        if (isset($info->excerpt)) {
            $page_description = $info->excerpt;
        }
        return view('info.detail', compact('page_title', 'page_keyword', 'page_description', 'info', 'infoCategory'));
    }

}

resources/views/admin/info/category/create_edit.blade.php
@extends('admin.layouts.page')

@section('css')
    <link href="{{ asset('assets/vendors/bootstrap3-wysihtml5-bower/css/bootstrap3-wysihtml5.min.css') }}" rel="stylesheet" media="screen" />
    <link href="{{ asset('assets/css/pages/editor.css') }}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/iCheck/css/all.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/iCheck/css/line/line.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/bootstrap-switch/css/bootstrap-switch.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/switchery/css/switchery.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/awesome-bootstrap-checkbox/css/awesome-bootstrap-checkbox.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/pages/radio_checkbox.css') }}">

    <link href="{{ asset('assets/vendors/jasny-bootstrap/css/jasny-bootstrap.css') }}" rel="stylesheet" />
    <link href="{{ asset('assets/vendors/intl-tel-input/css/intlTelInput.css') }}" rel="stylesheet" />
    <link href="{{ asset('assets/vendors/bootstrapvalidator/css/bootstrapValidator.min.css') }}" rel="stylesheet" />
    <link href="{{ asset('assets/css/pages/form2.css') }}" rel="stylesheet" />
    <link href="{{ asset('assets/css/pages/form3.css') }}" rel="stylesheet" />
    <link href="{{ asset('assets/vendors/bootstrap-touchspin/css/jquery.bootstrap-touchspin.css') }}" rel="stylesheet" type="text/css" media="all" />
    <link href="{{ asset('assets/vendors/jquery-spinner/css/bootstrap-spinner.css') }}" rel="stylesheet" />

@stop

@section('title', 'Aidlite')

@section('content_header')
    <h1>@if(isset($category->id))編輯@else新增@endif 資訊分類</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('admin.home') }}">
                <i class="livicon" data-name="home" data-size="16" data-color="#000"></i> Dashboard
            </a>
        </li>
        <li>
            <a href="{{ route('admin.news.categories.index') }}">資訊分類列表</a>
        </li>
        <li class="active">@if(isset($category->id))編輯@else新增@endif資訊分類</li>
    </ol>
@stop

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-info">
                @php
                    $url = route('admin.info.categories.store');
                    if(isset($category->id)) {
                        $url = route('admin.info.categories.update', ['id' => $category->id]);
                    }
                @endphp
                <div class="panel-heading">
                    <i class="livicon" data-name="adjust" data-size="18" data-c="white" data-hc="white" data-loop="true"></i>
                </div>
                <div class="panel-body border">
                    <form id="tryitForm" class="form-horizontal form-bordered" role="form" action="{{ $url }}" method="POST" enctype="multipart/form-data">
                        <!-- PUT Method if we are editing -->
                        @if(isset($category->id))
                            {{ method_field("PUT") }}
                        @endif
                        {{ csrf_field() }}
                        <!-- text input -->
                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-2">
                                <span class="text-primary">標題最大長度為16字(不分中英文)</span>
                            </div>
                            <label class="col-md-2 control-label" for="form-text-input">標題</label>
                            <div class="col-md-8">
                                <input type="text" id="form-text-input" name="name" class="form-control" placeholder="標題"
                                       value="@if(isset($category->name)){{ old('name', $category->name) }}@else{{ old('name') }}@endif" required>
                            </div>
                            @if ($errors->has('name'))
                                <div class="col-md-8 col-md-offset-2">
                                    <span class="text-danger">標題未填、長度過長或格式錯誤</span>
                                </div>
                            @endif
                        </div>
                        <div class="form-group">
                            <label class="col-md-2 control-label" for="form-text-input">狀態</label>
                            <div class="col-md-3">
                                <input type="checkbox" name="my-checkbox" @if(!isset($category->status) || $category->status == 1) checked @endif data-on-color="primary" data-off-color="info">
                            </div>
                            <label class="col-md-2 control-label " for="form-text-input">排序</label>
                            <div class="col-md-2 input-group spinner" data-trigger="spinner">
                                <input name="sort" type="text" class="form-control" value="@if(isset($category->sort)){{ old('sort', $category->sort) }}@else{{ old('sort') }}@endif" data-rule="quantity">
                                <div class="input-group-addon pickers_spinners">
                                    <a href="javascript:;" class="spin-up" data-spin="up"><i class="fa fa-chevron-up"></i></a>
                                    <a href="javascript:;" class="spin-down" data-spin="down"><i class="fa fa-chevron-down"></i></a>
                                </div>
                            </div>
                        </div>
                        <div class="form-group form-actions">
                            <div class="col-md-8 col-md-offset-2">
                                <button type="submit" class="btn btn-effect-ripple btn-primary">送出</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

@section('js')
    <script src="{{ asset('assets/vendors/tinymce/tinymce.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/vendors/ckeditor/js/ckeditor.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/vendors/ckeditor/js/jquery.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/vendors/ckeditor/js/config.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/js/pages/editor1.js') }}" type="text/javascript"></script>

    <script type="text/javascript" src="{{ asset('assets/vendors/iCheck/js/icheck.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/vendors/bootstrap-switch/js/bootstrap-switch.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/vendors/switchery/js/switchery.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/vendors/bootstrap-maxlength/js/bootstrap-maxlength.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/vendors/card/lib/js/jquery.card.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/radio_checkbox.js') }}"></script>
    <script src="{{ asset('assets/vendors/bootstrap-touchspin/js/jquery.bootstrap-touchspin.js') }}"></script>
    <script src="{{ asset('assets/vendors/jquery-spinner/js/jquery.spinner.min.js') }}"></script>
    <script src="{{ asset('assets/js/pages/pickers.js') }}"></script>
    <script>
        $("#fileUpload").on('change', function () {
            //Get count of selected files
            var countFiles = $(this)[0].files.length;
            var imgPath = $(this)[0].value;
            var extn = imgPath.substring(imgPath.lastIndexOf('.') + 1).toLowerCase();
            var image_holder = $("#preview");
            image_holder.empty();
            console.log(imgPath);
            if (extn == "gif" || extn == "png" || extn == "jpg" || extn == "jpeg") {
                if (typeof (FileReader) != "undefined") {
                    //loop for each file selected for uploaded.
                    for (var i = 0; i < countFiles; i++) {
                        var reader = new FileReader();
                        reader.onload = function (e) {
                            $('#preview').attr('src',e.target.result);
                            $('#preview').attr('class',"thumb-image");
                        }
                        reader.readAsDataURL($(this)[0].files[i]);
                    }
                } else {
                    alert("This browser does not support FileReader.");
                }
            } else {
                alert("Pls select only images");
            }
        });

        function chaneImage(val) {
            console.log(val);
            $('#preview').attr('src',val);
            $('#preview').attr('class',"thumb-image");
        }
    </script>
@stop

resources/views/admin/info/category/index.blade.php
@extends('admin.layouts.page')

@section('title', 'Aidlite')

@section('content_header')
    <h1>資訊分類列表</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('admin.home') }}">
                <i class="livicon" data-name="home" data-size="16" data-color="#000"></i> Dashboard
            </a>
        </li>
        <li class="active">
            資訊分類列表
        </li>

    </ol>
@stop

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-info filterable">
                <div class="panel-heading clearfix">
                    <div class="pull-left">
                        <i class="livicon" data-name="bell" data-size="18" data-c="white" data-hc="white" data-loop="true"></i>
                    </div>
                    <div class="pull-right">
                        <a href="{{ route('admin.info.categories.create') }}" class="btn btn-primary btn-sm">
                            <span><i class="fa fa-plus" id="addButton"></i>&nbsp;&nbsp;新增資訊分類</span>
                        </a>
                    </div>
                </div>
                <div class="panel-body table-responsive">
                    <table class="table" id="table3">
                        <thead>
                        <tr>
                            <th>名稱</th>
                            <th>狀態</th>
                            <th>排序</th>
                            <th>時間</th>
                            <th>動作</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($categories as $category)
                            <tr>
                                <td>{{ $category->name }}</td>
                                <td>
                                    @if ($category->status)
                                        開啟
                                    @else
                                        關閉
                                    @endif
                                </td>
                                <td>{{ $category->sort }}</td>
                                <td>{{ $category->updated_at }}</td>
                                <td>
                                    <a href="{{ route('admin.info.categories.edit', ['id' => $category->id]) }}">
                                        <span class="btn btn-success"><i class="fa fa-edit"></i></span>
                                    </a>
                                    <a href="#modal-danger" data-toggle="modal" data-target="#modal-danger" data-variable="{{ route('admin.info.categories.destroy', ['id' => $category->id]) }}">
                                        <span class="btn btn-danger"><i class="fa fa-trash"></i></span>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            {!! $categories->links() !!}
        </div>
    </div>
    <!--window-->
    <div class="modal fade" id="modal-danger" role="document">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-primary">
                    <button type="button" class="close white" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                    <h4><i class="icon fa fa-ban"></i> 提醒</h4>
                </div>
                <div class="modal-body">
                    <p>確定要刪除嗎？</p>
                </div>
                <div class="modal-footer">

                    <form action="" id="delete_form" method="POST">
                        {{ method_field("DELETE") }}
                        {{ csrf_field() }}
                        <button type="button" data-dismiss="modal" class="btn btn-default">取消</button>
                        <input type="submit" class="btn btn-primary" value="確定">
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!--window-->
@stop

@section('js')

    <script type="application/javascript">

        $('#modal-danger').on('show.bs.modal', function(e) {
            var $target = $(e.relatedTarget);
            var variable = $target.attr('data-variable');
            console.log(variable);
            $('#delete_form').attr('action', variable);

        })

    </script>

@stop