routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

//about
Route::get('/about', 'AboutController@index');

//Product
Route::get('/productCategories', 'ProductCategoryController@index');
Route::get('/productCategories/{id}', 'ProductCategoryController@show');
Route::get('/product/{id}', 'ProductController@index');
Route::get('/products/search', 'ProductCategoryController@search')->name('product.search');
Route::get('/products/specifications/search', 'ProductCategoryController@searchSpecifications')->name('product.specification.search');

//Info
Route::get('/infoCategories', 'InfoCategoryController@index');
Route::get('/infoCategories/{id}', 'InfoCategoryController@show');
Route::get('/info/{id}', 'InfoController@index');

//News
Route::get('/newsCategories', 'NewsCategoryController@index');
Route::get('/newsCategories/{id}', 'NewsCategoryController@show');
Route::get('/news/{id}', 'NewsController@index');

//Contact
Route::get('/contact', 'ContactController@index');

//Send Mail
Route::get('/sendemail', 'ContactController@send');

//inquiry car
Route::get('/inquiry_car', 'ContactController@inquiry');

//Send Mail
Route::get('/inquiry_send', 'ContactController@inquiry_send');
/*
Route::get('/', function () {
    return view('layouts.default');
});
*/

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () {

    Route::get('/', 'ProductsController@index')->name('home');
    Route::get('/home', 'ProductsController@index')->name('home.index');

    //Route::get('/news/categories', 'NewsCategoriesController@index')->name('admin.news.category.index');
    Route::resource('/news/categories', 'NewsCategoriesController', [
        'as' => 'news'
    ]);
    Route::resource('/news', 'NewsController');
    Route::resource('/info/categories', 'InfoCategoriesController', [
        'as' => 'info'
    ]);
    Route::resource('/info', 'InfoController');
    Route::resource('/banner/categories', 'BannersCategoriesController', [
        'as' => 'banner'
    ]);
    Route::resource('/banners', 'BannersController');
    Route::resource('/sub/banners', 'SubBannersController', [
        'as' => 'sub'
    ]);
    Route::resource('/product/categories', 'ProductCategoriesController', [
        'as' => 'product'
    ]);
    Route::resource('/product/specification/categories', 'SpecificationCategoriesController', [
        'as' => 'product.specification'
    ]);
    
    Route::get('/product/specifications/list', 'SpecificationsController@list')->name('product.specifications.list');
    Route::resource('/product/specifications', 'SpecificationsController', [
        'as' => 'product'
    ]);

    Route::get('/product/specifications_by_category/{id}', 'SpecificationsController@specificationsByCategoryID');

    Route::resource('/product/specification/items', 'SpecificationItemsController', [
        'as' => 'product.specification'
    ]);
    Route::resource('/products', 'ProductsController');
    Route::get('/products/{id}/copy', 'ProductsController@copy')->name('products.copy');

    Route::get('/about', 'PagesController@index')->name('page.index');
    Route::put('/about/{id}', 'PagesController@update')->name('page.update');
    Route::post('/about', 'PagesController@store')->name('page.store');

    Route::post('/upload/images', 'ImagesController@upload');
    Route::post('/upload/images/delete', 'ImagesController@destroy');
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('/admin/laravel-filemanager', '\UniSharp\LaravelFilemanager\Controllers\LfmController@show');
    Route::post('/admin/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\Controllers\UploadController@upload');
    // list all lfm routes here...
});

Auth::routes();

resources/views/admin/page/create_edit.blade.php
@extends('admin.layouts.page')

@section('css')
    <link href="{{ asset('assets/vendors/bootstrap3-wysihtml5-bower/css/bootstrap3-wysihtml5.min.css') }}" rel="stylesheet" media="screen" />
    <link href="{{ asset('assets/css/pages/editor.css') }}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/iCheck/css/all.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/iCheck/css/line/line.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/bootstrap-switch/css/bootstrap-switch.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/switchery/css/switchery.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/awesome-bootstrap-checkbox/css/awesome-bootstrap-checkbox.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/pages/radio_checkbox.css') }}">

    <link href="{{ asset('assets/vendors/jasny-bootstrap/css/jasny-bootstrap.css') }}" rel="stylesheet" />
    <link href="{{ asset('assets/vendors/intl-tel-input/css/intlTelInput.css') }}" rel="stylesheet" />
    <link href="{{ asset('assets/vendors/bootstrapvalidator/css/bootstrapValidator.min.css') }}" rel="stylesheet" />
    <link href="{{ asset('assets/css/pages/form2.css') }}" rel="stylesheet" />
    <link href="{{ asset('assets/css/pages/form3.css') }}" rel="stylesheet" />

@stop

@section('title', 'Aidlite')

@section('content_header')
    <h1>關於我們</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('admin.home') }}">
                <i class="livicon" data-name="home" data-size="16" data-color="#000"></i> Dashboard
            </a>
        </li>
        <li class="active">關於我們</li>
    </ol>
@stop

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-info">
                @php
                    $url = route('admin.page.store');
                    if(isset($page->id)) {
                        $url = route('admin.page.update', ['id' => $page->id]);
                    }
                @endphp
                <div class="panel-heading">
                    <i class="livicon" data-name="info" data-size="18" data-c="white" data-hc="white" data-loop="true"></i>
                </div>
                <div class="panel-body border">
                    <form id="tryitForm" class="form-horizontal form-bordered" role="form" action="{{ $url }}" method="POST">
                        <!-- PUT Method if we are editing -->
                        @if(isset($page->id))
                            {{ method_field("PUT") }}
                        @endif
                        {{ csrf_field() }}
                        <!-- text input -->
                        <div class="form-group">
                            <label class="col-md-2 control-label" for="form-textarea-input">內容</label>
                            <div class="col-md-8 bootstrap-admin-panel-content">
                                <textarea name="content" class="form-control my-editor" style="height: 300px;">@if (isset($page->content)){{ old('content', $page->content) }}@else{{ old('content') }}@endif</textarea>
                            </div>
                            @if ($errors->has('content'))
                                <div class="col-md-8 col-md-offset-2">
                                    <span class="text-danger">內容未填或格式錯誤</span>
                                </div>
                            @endif
                        </div>


                        <div class="form-group form-actions">
                            <div class="col-md-8 col-md-offset-2">
                                <button id="Submit" type="submit" class="btn btn-effect-ripple btn-primary">送出</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

@section('js')
    <script src="{{ asset('assets/vendors/tinymce/tinymce.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/vendors/ckeditor/js/ckeditor.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/vendors/ckeditor/js/jquery.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/vendors/ckeditor/js/config.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/js/pages/editor1.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/js/pages/validation.js') }}" type="text/javascript"></script>
    <script type="text/javascript" src="{{ asset('assets/vendors/iCheck/js/icheck.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/vendors/bootstrap-switch/js/bootstrap-switch.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/vendors/switchery/js/switchery.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/vendors/bootstrap-maxlength/js/bootstrap-maxlength.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/vendors/card/lib/js/jquery.card.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/radio_checkbox.js') }}"></script>

    <script>
        var editor_config = {
            path_absolute : "/admin/",
            selector: "textarea.my-editor",
            language:'zh_TW',
            plugins: [
                "advlist autolink lists link image charmap print preview hr anchor pagebreak",
                "searchreplace wordcount visualblocks visualchars code fullscreen",
                "insertdatetime media nonbreaking save table contextmenu directionality",
                "emoticons template paste textcolor colorpicker textpattern"
            ],
            toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
            relative_urls: false,
            file_browser_callback : function(field_name, url, type, win) {
                var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
                var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

                var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
                if (type == 'image') {
                    cmsURL = cmsURL + "&type=Images";
                } else {
                    cmsURL = cmsURL + "&type=Files";
                }

                tinyMCE.activeEditor.windowManager.open({
                    file : cmsURL,
                    title : 'Filemanager',
                    width : x * 0.8,
                    height : y * 0.8,
                    resizable : "yes",
                    close_previous : "no"
                });
            }
        };

        tinymce.init(editor_config);

        $('#Submit').click(function() {
            alert('儲存完畢!!');
        });
    </script>
@stop

resources/views/admin/page/index.blade.php
@extends('admin.layouts.page')

@section('title', 'Aidlite')

@section('content_header')
    <h1>消息列表</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('admin.home') }}">
                <i class="livicon" data-name="home" data-size="16" data-color="#000"></i> Dashboard
            </a>
        </li>
        <li class="active">
            消息列表
        </li>

    </ol>
@stop

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-info filterable">
                <div class="panel-heading clearfix">
                    <div class="pull-left">
                        <i class="livicon" data-name="bell" data-size="18" data-c="white" data-hc="white" data-loop="true"></i>
                    </div>
                    <div class="pull-right">
                        <a href="{{ route('admin.news.create') }}" class="btn btn-primary btn-sm">
                            <span><i class="fa fa-plus" id="addButton"></i>&nbsp;&nbsp;新增消息</span>
                        </a>
                    </div>
                </div>
                <div class="panel-body table-responsive">
                    <table class="table" id="table3">
                        <thead>
                        <tr>
                            <th>標題</th>
                            <th>分類</th>
                            <th>摘要</th>
                            <th>狀態</th>
                            <th>建立時間</th>
                            <th>動作</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($newsList as $news)
                            <tr>
                                <td>{{ $news->title }}</td>
                                <td>{{ $news->category['name'] }}</td>
                                <td>{{ $news->excerpt }}</td>
                                <td>
                                    @if ($news->status)
                                        開啟
                                    @else
                                        關閉
                                    @endif
                                </td>
                                <td>{{ $news->created_at }}</td>
                                <td>
                                    <a href="/news/{{  $news->id }}">
                                        <span class="btn btn-info"><i class="fa fa-eye"></i></span>
                                    </a>
                                    <a href="{{ route('admin.news.edit', ['id' => $news->id]) }}">
                                        <span class="btn btn-success"><i class="fa fa-edit"></i></span>
                                    </a>
                                    <a href="#modal-danger" data-toggle="modal" data-target="#modal-danger" data-variable="{{ route('admin.news.destroy', ['id' => $news->id]) }}">
                                        <span class="btn btn-danger"><i class="fa fa-trash"></i></span>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            {!! $newsList->links() !!}
        </div>
    </div>

    <!--window-->
    <div class="modal fade" id="modal-danger" role="document">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-primary">
                    <button type="button" class="close white" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                    <h4><i class="icon fa fa-ban"></i> 提醒</h4>
                </div>
                <div class="modal-body">
                    <p>確定要刪除嗎？</p>
                </div>
                <div class="modal-footer">

                    <form action="" id="delete_form" method="POST">
                        {{ method_field("DELETE") }}
                        {{ csrf_field() }}
                        <button type="button" data-dismiss="modal" class="btn btn-default">取消</button>
                        <input type="submit" class="btn btn-primary" value="確定">
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!--window-->
@stop

@section('js')
    <script>

        $('#modal-danger').on('show.bs.modal', function(e) {
            var $target = $(e.relatedTarget);
            var variable = $target.attr('data-variable');
            console.log(variable);
            $('#delete_form').attr('action', variable);
//            var $modal = $(this);
//            var esseyId = e.relatedTarget.id;
//            $modal.find('.modal-body').html(esseyId);
        })

    </script>
@stop

resources/views/admin/page/show.blade.php
@extends('admin.layouts.page')

@section('title', 'Aidlite')

@section('css')
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.css') }}" />
    <link href="{{ asset('assets/css/pages/alertmessage.css') }}" rel="stylesheet" type="text/css" />

@stop

@section('content_header')

    <h1>消息</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('admin.home') }}">
                <i class="livicon" data-name="home" data-size="16" data-color="#000"></i> Dashboard
            </a>
        </li>
        <li>
            <a href="{{ route('admin.news.index') }}">消息列表</a>
        </li>
        <li class="active">消息</li>
    </ol>

@stop

@section('content')

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-warning">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <i class="livicon" data-name="notebook" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>{{ $news->category['name'] }}
                    </h3>
                    <span class="pull-right">{{ $news->created_at }}</span>
                </div>
                <div class="panel-body">
                    <div class="alert-message alert-message-success">
                        <h4>{{ $news->title }}</h4>
                        <p>{{ $news->excerpt }}</p>
                    </div>
                    <div>{!! html_entity_decode($news->body) !!}</div>
                </div>
            </div>
        </div>
    </div>
@stop