routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

//about
Route::get('/about', 'AboutController@index');

//Product
Route::get('/productCategories', 'ProductCategoryController@index');
Route::get('/productCategories/{id}', 'ProductCategoryController@show');
Route::get('/product/{id}', 'ProductController@index');
Route::get('/products/search', 'ProductCategoryController@search')->name('product.search');
Route::get('/products/specifications/search', 'ProductCategoryController@searchSpecifications')->name('product.specification.search');

//Info
Route::get('/infoCategories', 'InfoCategoryController@index');
Route::get('/infoCategories/{id}', 'InfoCategoryController@show');
Route::get('/info/{id}', 'InfoController@index');

//News
Route::get('/newsCategories', 'NewsCategoryController@index');
Route::get('/newsCategories/{id}', 'NewsCategoryController@show');
Route::get('/news/{id}', 'NewsController@index');

//Contact
Route::get('/contact', 'ContactController@index');

//Send Mail
Route::get('/sendemail', 'ContactController@send');

//inquiry car
Route::get('/inquiry_car', 'ContactController@inquiry');

//Send Mail
Route::get('/inquiry_send', 'ContactController@inquiry_send');
/*
Route::get('/', function () {
    return view('layouts.default');
});
*/

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () {

    Route::get('/', 'ProductsController@index')->name('home');
    Route::get('/home', 'ProductsController@index')->name('home.index');

    //Route::get('/news/categories', 'NewsCategoriesController@index')->name('admin.news.category.index');
    Route::resource('/news/categories', 'NewsCategoriesController', [
        'as' => 'news'
    ]);
    Route::resource('/news', 'NewsController');
    Route::resource('/info/categories', 'InfoCategoriesController', [
        'as' => 'info'
    ]);
    Route::resource('/info', 'InfoController');
    Route::resource('/banner/categories', 'BannersCategoriesController', [
        'as' => 'banner'
    ]);
    Route::resource('/banners', 'BannersController');
    Route::resource('/sub/banners', 'SubBannersController', [
        'as' => 'sub'
    ]);
    Route::resource('/product/categories', 'ProductCategoriesController', [
        'as' => 'product'
    ]);
    Route::resource('/product/specification/categories', 'SpecificationCategoriesController', [
        'as' => 'product.specification'
    ]);
    
    Route::get('/product/specifications/list', 'SpecificationsController@list')->name('product.specifications.list');
    Route::resource('/product/specifications', 'SpecificationsController', [
        'as' => 'product'
    ]);

    Route::get('/product/specifications_by_category/{id}', 'SpecificationsController@specificationsByCategoryID');

    Route::resource('/product/specification/items', 'SpecificationItemsController', [
        'as' => 'product.specification'
    ]);
    Route::resource('/products', 'ProductsController');
    Route::get('/products/{id}/copy', 'ProductsController@copy')->name('products.copy');

    Route::get('/about', 'PagesController@index')->name('page.index');
    Route::put('/about/{id}', 'PagesController@update')->name('page.update');
    Route::post('/about', 'PagesController@store')->name('page.store');

    Route::post('/upload/images', 'ImagesController@upload');
    Route::post('/upload/images/delete', 'ImagesController@destroy');
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('/admin/laravel-filemanager', '\UniSharp\LaravelFilemanager\Controllers\LfmController@show');
    Route::post('/admin/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\Controllers\UploadController@upload');
    // list all lfm routes here...
});

Auth::routes();

app/Models/SubBanner.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class SubBanner extends Model
{
    protected $fillable = ['name', 'alt', 'url', 'target', 'status', 'sort'];

    public function scopePublish($query)
    {
        return $query->where('status', 1);
    }

    public function images()
    {
        return $this->hasMany('App\Models\Image', 'relation_id', 'id')->where('type', 'subbanner')->orderBy('sort');
    }
}

app/Http/Controllers/Admin/SubBannersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Repositories\ImageRepository;
use App\Repositories\SubBannerRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Intervention\Image\Facades\Image;

class SubBannersController extends Controller
{
    protected $repository;
    protected $imageRepository;

    public function __construct(SubBannerRepository $repository, ImageRepository $imageRepository)
    {
        $this->middleware('auth');
        $this->repository = $repository;
        $this->imageRepository = $imageRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $banners = $this->repository->bannersWithPaging();

        //dd($banners);
        return view('admin.subbanner.index', compact('banners'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('admin.subbanner.create_edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $validator = Validator::make($request->all(),[
            'name' => 'required',
            'images' => 'required',
        ]);

        if ($validator->fails()) {
            $messages = $validator->messages();
            //dd($messages);
            return response()->json([
                'status' => 'error',
                'data' => [
                    'message' => $messages,
                ]
            ]);
        }

        //dd($request->all());
        $data = array();
        $data['name'] = $request->get('name');
        
        $url = $request->get('url');
        if (isset($url)) {
            $data['url'] = $url;
        } else {
            $data['url'] = null;
        }
        
        $data['status'] = $request->get('my-checkbox') === 'on'?1:0;
        $data['sort'] = $request->get('sort');

        //dd($data);
        $banner = $this->repository->create($data);

        $images = json_decode($request->get('images'), true);

        $this->imageRepository->changeTempByRelationAndType($banner->id, "subbanner", false);

        foreach($images as $key => $data) {
            $image = $this->imageRepository->image($data);
            if (isset($image)) {
                $image->relation_id = $banner->id;
                $image->sort = $key;
                $image->is_temp = true;
                $image->save();
            }
        }
        $this->imageRepository->deleteByTemp();

        return response()->json([
            'status' => 'success',
        ]);
        //return redirect()->route('admin.sub.banner.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $banner = $this->repository->banner($id);

        //dd($news);
        return view('admin.subbanner.show', compact('banner'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $banner = $this->repository->banner($id);

        //dd($news);
        return view('admin.subbanner.create_edit', compact('banner'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

//        return response()->json([
//            'status' => 'success',
//            'data' => $request->all(),
//        ]);
        $validator = Validator::make($request->all(),[
            'name' => 'required',
            'images' => 'required',
        ]);

        if ($validator->fails()) {
            $messages = $validator->messages();
            //dd($messages);
            return response()->json([
                'status' => 'error',
                'data' => [
                    'message' => $messages,
                ]
            ]);
        }

        //dd($request->all());
        $banner = $this->repository->banner($id);
        $banner->name = $request->get('name');
        

        $url = $request->get('url');
        if (isset($url)) {
            $banner->url = $url;
        } else {
            $banner->url = null;
        }
        
        $banner->status = $request->get('my-checkbox') === 'on'?1:0;
        $banner->sort = $request->get('sort');
        //dd($data);
        $banner->save();

        $images = json_decode($request->get('images'), true);

        $this->imageRepository->changeTempByRelationAndType($id, "subbanner", false);

        foreach($images as $key => $data) {
            $image = $this->imageRepository->image($data);
            if (isset($image)) {
                $image->relation_id = $banner->id;
                $image->sort = $key;
                $image->is_temp = true;
                $image->save();
            }
        }
        $this->imageRepository->deleteByTemp();

        return response()->json([
            'status' => 'success',
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //dd($id);
        $banner = $this->repository->banner($id);
        if ($banner) {
            $this->imageRepository->deleteByRelationAndType($banner->id, "subbanner");
            $this->repository->delete($id);
        }

        return redirect()->route('admin.sub.banners.index');
    }
}

resources/views/admin/subbanner/index.blade.php
@extends('admin.layouts.page')

@section('title', 'Aidlite')

@section('content_header')
    <h1>SubBanner 列表</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('admin.home') }}">
                <i class="livicon" data-name="home" data-size="16" data-color="#000"></i> Dashboard
            </a>
        </li>
        <li class="active">
            SubBanner 列表
        </li>

    </ol>
@stop

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-info filterable">
                <div class="panel-heading clearfix">
                    <div class="pull-left">
                        <i class="livicon" data-name="image" data-size="18" data-c="white" data-hc="white" data-loop="true"></i>
                    </div>
                    <div class="pull-right">
                        <a href="{{ route('admin.sub.banners.create') }}" class="btn btn-primary btn-sm">
                            <span><i class="fa fa-plus" id="addButton"></i>&nbsp;&nbsp;新增 SubBanner</span>
                        </a>
                    </div>
                </div>
                <div class="panel-body table-responsive">
                    <table class="table" id="table3">
                        <thead>
                        <tr>
                            <th>圖</th>
                            <th>標題</th>
                            <th>連結</th>
                            <th>狀態</th>
                            <th>時間</th>
                            <th>動作</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($banners as $banner)
                            <tr>
                                <td><img class="news-block-img" src="@if(isset($banner->images[0]->image)){{ Storage::url($banner->images[0]->image) }}@endif" data-src="@if(isset($banner->images[0]->image)){{ Storage::url($banner->images[0]->image) }}@endif" alt="@if(isset($banner->images[0]->image)){{ Storage::url($banner->images[0]->image) }}@endif" style="width: 50px;"></td>
                                <td>{{ $banner->name }}</td>
                                <td>{{ $banner->url }}</td>
                                <td>
                                    @if ($banner->status)
                                        開啟
                                    @else
                                        關閉
                                    @endif
                                </td>
                                <td>{{ $banner->updated_at }}</td>
                                <td>
                                    <!--a href="{{ route('admin.sub.banners.show', ['id' => $banner->id]) }}">
                                        <span class="btn btn-info"><i class="fa fa-eye"></i></span>
                                    </a-->
                                    <a href="{{ route('admin.sub.banners.edit', ['id' => $banner->id]) }}">
                                        <span class="btn btn-success"><i class="fa fa-edit"></i></span>
                                    </a>
                                    <a href="#modal-danger" data-toggle="modal" data-target="#modal-danger" data-variable="{{ route('admin.sub.banners.destroy', ['id' => $banner->id]) }}">
                                        <span class="btn btn-danger"><i class="fa fa-trash"></i></span>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            {!! $banners->links() !!}
        </div>
    </div>

    <!--window-->
    <div class="modal fade" id="modal-danger" role="document">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-primary">
                    <button type="button" class="close white" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                    <h4><i class="icon fa fa-ban"></i> 提醒</h4>
                </div>
                <div class="modal-body">
                    <p>確定要刪除嗎？</p>
                </div>
                <div class="modal-footer">

                    <form action="" id="delete_form" method="POST">
                        {{ method_field("DELETE") }}
                        {{ csrf_field() }}
                        <button type="button" data-dismiss="modal" class="btn btn-default">取消</button>
                        <input type="submit" class="btn btn-primary" value="確定">
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!--window-->
@stop

@section('js')
    <script>

        $('#modal-danger').on('show.bs.modal', function (e) {
            var $target = $(e.relatedTarget);
            var variable = $target.attr('data-variable');
            console.log(variable);
            $('#delete_form').attr('action', variable);
        });

    </script>
@stop

resources/views/admin/subbanner/show.blade.php
@extends('admin.layouts.page')

@section('title', 'Aidlite')

@section('css')
    <link rel="stylesheet" type="text/css" href="{{ asset('admin/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.css') }}" />
    <link href="{{ asset('admin/css/pages/alertmessage.css') }}" rel="stylesheet" type="text/css" />

@stop

@section('content_header')

    <h1>消息</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('admin.home') }}">
                <i class="livicon" data-name="home" data-size="16" data-color="#000"></i> Dashboard
            </a>
        </li>
        <li>
            <a href="{{ route('admin.banners.index') }}">Banner 列表</a>
        </li>
        <li class="active">Banner</li>
    </ol>

@stop

@section('content')

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-warning">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <i class="livicon" data-name="image" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                    </h3>
                    <span class="pull-right">{{ $banner->created_at }}</span>
                </div>
                <div class="panel-body">
                    <div>
                        @if(isset($banner->url))
                            <a href="{{ $banner->url }}" target="{{ $banner->target }}">
                        @endif
                        <img class="news-block-img" src="{{ Storage::url($banner->images[0]->image) }}" data-src="{{ Storage::url($banner->images[0]->image) }}" alt=@if(isset($banner->alt))"{{ $banner->alt }}"@else"{{ $banner->name }}"@endif style="height: 300px;">
                        @if(isset($banner->url))
                            </a>
                        @endif
                    </div>

                </div>
            </div>
        </div>
    </div>
@stop