routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

//about
Route::get('/about', 'AboutController@index');

//Product
Route::get('/productCategories', 'ProductCategoryController@index');
Route::get('/productCategories/{id}', 'ProductCategoryController@show');
Route::get('/product/{id}', 'ProductController@index');
Route::get('/products/search', 'ProductCategoryController@search')->name('product.search');
Route::get('/products/specifications/search', 'ProductCategoryController@searchSpecifications')->name('product.specification.search');

//Info
Route::get('/infoCategories', 'InfoCategoryController@index');
Route::get('/infoCategories/{id}', 'InfoCategoryController@show');
Route::get('/info/{id}', 'InfoController@index');

//News
Route::get('/newsCategories', 'NewsCategoryController@index');
Route::get('/newsCategories/{id}', 'NewsCategoryController@show');
Route::get('/news/{id}', 'NewsController@index');

//Contact
Route::get('/contact', 'ContactController@index');

//Send Mail
Route::get('/sendemail', 'ContactController@send');

//inquiry car
Route::get('/inquiry_car', 'ContactController@inquiry');

//Send Mail
Route::get('/inquiry_send', 'ContactController@inquiry_send');
/*
Route::get('/', function () {
    return view('layouts.default');
});
*/

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () {

    Route::get('/', 'ProductsController@index')->name('home');
    Route::get('/home', 'ProductsController@index')->name('home.index');

    //Route::get('/news/categories', 'NewsCategoriesController@index')->name('admin.news.category.index');
    Route::resource('/news/categories', 'NewsCategoriesController', [
        'as' => 'news'
    ]);
    Route::resource('/news', 'NewsController');
    Route::resource('/info/categories', 'InfoCategoriesController', [
        'as' => 'info'
    ]);
    Route::resource('/info', 'InfoController');
    Route::resource('/banner/categories', 'BannersCategoriesController', [
        'as' => 'banner'
    ]);
    Route::resource('/banners', 'BannersController');
    Route::resource('/sub/banners', 'SubBannersController', [
        'as' => 'sub'
    ]);
    Route::resource('/product/categories', 'ProductCategoriesController', [
        'as' => 'product'
    ]);
    Route::resource('/product/specification/categories', 'SpecificationCategoriesController', [
        'as' => 'product.specification'
    ]);
    
    Route::get('/product/specifications/list', 'SpecificationsController@list')->name('product.specifications.list');
    Route::resource('/product/specifications', 'SpecificationsController', [
        'as' => 'product'
    ]);

    Route::get('/product/specifications_by_category/{id}', 'SpecificationsController@specificationsByCategoryID');

    Route::resource('/product/specification/items', 'SpecificationItemsController', [
        'as' => 'product.specification'
    ]);
    Route::resource('/products', 'ProductsController');
    Route::get('/products/{id}/copy', 'ProductsController@copy')->name('products.copy');

    Route::get('/about', 'PagesController@index')->name('page.index');
    Route::put('/about/{id}', 'PagesController@update')->name('page.update');
    Route::post('/about', 'PagesController@store')->name('page.store');

    Route::post('/upload/images', 'ImagesController@upload');
    Route::post('/upload/images/delete', 'ImagesController@destroy');
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('/admin/laravel-filemanager', '\UniSharp\LaravelFilemanager\Controllers\LfmController@show');
    Route::post('/admin/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\Controllers\UploadController@upload');
    // list all lfm routes here...
});

Auth::routes();

app/Models/Specification.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Specification extends Model
{
    protected $fillable = ['name', 'category_id', 'sort'];

    public function category()
    {
        return $this->belongsTo('App\Models\SpecificationCategory', 'category_id', 'id');
    }

    public function items()
    {
        return $this->hasMany('App\Models\SpecificationItem', 'specification_id', 'id')->orderBy('sort');
    }
}

app/Http/Controllers/Admin/SpecificationsController.php
<?php

namespace App\Http\Controllers\Admin;


use App\Repositories\SpecificationCategoryRepository;
use App\Repositories\SpecificationRepository;
use App\Repositories\SpecificationItemRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Validator;

class SpecificationsController extends Controller
{
    protected $repository;
    protected $category;
    protected $specificationItem;

    public function __construct(SpecificationRepository $repository, SpecificationCategoryRepository $category, SpecificationItemRepository $specificationItem)
    {
        $this->repository = $repository;
        $this->category = $category;
        $this->specificationItem = $specificationItem;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function list()
    {
        //$items = $this->repository->specificationsWithCategoryAndPaging();
        $categories = $this->category->categoriesWithPaging();

        //dd($items);
        return view('admin.product.specification.list', compact('categories'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $category_id = $request->get('id');
        $items = $this->repository->specificationsWithCategoryAndPaging($category_id);
        //dd($items);
        return view('admin.product.specification.index', compact('items', 'category_id'));
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $categories = $this->category->categories();
        $category_id = $request->get('category_id');
        return view('admin.product.specification.create_edit', compact('categories', 'category_id'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(),[
            'name' => 'required',
        ]);

        if ($validator->fails()) {
            $messages = $validator->messages();
            //dd($messages);
            return Redirect::back()
                ->withErrors($validator)
                ->withInput();
        }

        //dd($request->all());
        $data = array();
        $data['name'] = $request->get('name');
        $data['sort'] = $request->get('sort');
        $data['category_id'] = $request->get('category_id');

        //dd($data);
        $this->repository->create($data);

        return redirect()->route('admin.product.specifications.index', ['id' => $data['category_id']]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $item = $this->repository->specification($id);

        //dd($category);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id, Request $request)
    {
        $categories = $this->category->categories();
        $item = $this->repository->specification($id);
        $category_id = $request->get('category_id');
        return view('admin.product.specification.create_edit', compact('categories', 'item', 'category_id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(),[
            'name' => 'required',
            'category_id' => 'required',
        ]);

        if ($validator->fails()) {
            $messages = $validator->messages();
            //dd($messages);
            return Redirect::back()
                ->withErrors($validator)
                ->withInput();
        }

        //dd($request->all());
        $item = $this->repository->specification($id);
        $item->name = $request->get('name');
        $item->sort = $request->get('sort');
        $item->category_id = $request->get('category_id');

        $item->save();

        return redirect()->route('admin.product.specifications.index', ['id' => $request->get('category_id')]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        //dd($request->get('category_id'));
        $error = 0;
        $count = $this->specificationItem->specificationItemCountBySpecification($id);
        //dd($count);
        if ($count <= 0) {
            $this->repository->delete($id);
        } else {
            $error = 1;
        }

        return redirect()->route('admin.product.specifications.index', ['id' => $request->get('category_id')])->with('error', $error);
    }

    public function specificationsByCategoryID(Request $request, $id)
    {
        if (!isset($id)) {
            return response()->json([
                'message' => '無此分類',
                'status' => 'error'
            ]);
        }

        $specifications = $this->repository->specificationsWithItemsByCategory($id);

        return response()->json([
            'status' => 'success',
            'data' => $specifications
        ]);
    }

}

resources/views/admin/product/specification/item/create_edit.blade.php
@extends('admin.layouts.page')

@section('css')
    <link href="{{ asset('assets/vendors/bootstrap3-wysihtml5-bower/css/bootstrap3-wysihtml5.min.css') }}" rel="stylesheet" media="screen" />
    <link href="{{ asset('assets/css/pages/editor.css') }}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/iCheck/css/all.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/iCheck/css/line/line.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/bootstrap-switch/css/bootstrap-switch.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/switchery/css/switchery.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/awesome-bootstrap-checkbox/css/awesome-bootstrap-checkbox.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/pages/radio_checkbox.css') }}">

    <link href="{{ asset('assets/vendors/jasny-bootstrap/css/jasny-bootstrap.css') }}" rel="stylesheet" />
    <link href="{{ asset('assets/vendors/intl-tel-input/css/intlTelInput.css') }}" rel="stylesheet" />
    <link href="{{ asset('assets/vendors/bootstrapvalidator/css/bootstrapValidator.min.css') }}" rel="stylesheet" />
    <link href="{{ asset('assets/css/pages/form2.css') }}" rel="stylesheet" />
    <link href="{{ asset('assets/css/pages/form3.css') }}" rel="stylesheet" />
    <link href="{{ asset('assets/vendors/bootstrap-touchspin/css/jquery.bootstrap-touchspin.css') }}" rel="stylesheet" type="text/css" media="all" />
    <link href="{{ asset('assets/vendors/jquery-spinner/css/bootstrap-spinner.css') }}" rel="stylesheet" />

@stop

@section('title', 'Aidlite')

@section('content_header')
    <h1>@if(isset($item->id))編輯@else新增@endif 產品規格項目</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('admin.home') }}">
                <i class="livicon" data-name="home" data-size="16" data-color="#000"></i> Dashboard
            </a>
        </li>
        <li>
            <a href="{{ route('admin.product.specifications.list') }}">產品規格分類列表</a>
        </li>
        <li>
            <a href="{{ route('admin.product.specifications.index', ['id' => $specification_id]) }}">產品規格列表</a>
        </li>
        <li>
            <a href="{{ route('admin.product.specification.items.index', ['id' => $specification_id]) }}">產品規格項目列表</a>
        </li>
        <li class="active">@if(isset($item->id))編輯@else新增@endif產品規格項目</li>
    </ol>
@stop

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-info">
                @php
                    $url = route('admin.product.specification.items.store');
                    if(isset($item->id)) {
                        $url = route('admin.product.specification.items.update', ['id' => $item->id]);
                    }
                @endphp
                <div class="panel-heading">
                    <i class="livicon" data-name="adjust" data-size="18" data-c="white" data-hc="white" data-loop="true"></i>
                </div>
                <div class="panel-body border">
                    <form id="tryitForm" class="form-horizontal form-bordered" role="form" action="{{ $url }}" method="POST" enctype="multipart/form-data">
                        <!-- PUT Method if we are editing -->
                        @if(isset($item->id))
                            {{ method_field("PUT") }}
                        @endif
                        {{ csrf_field() }}
                        <!-- text input -->
                        <div class="form-group">
                            <label class="col-md-2 control-label" for="form-text-input">標題</label>
                            <div class="col-md-8">
                                <input type="text" id="form-text-input" name="name" class="form-control" placeholder="標題"
                                       value="@if(isset($item->name)){{ old('name', $item->name) }}@else{{ old('name') }}@endif" required>
                            </div>
                            @if ($errors->has('name'))
                                <div class="col-md-8 col-md-offset-2">
                                    <span class="text-danger">標題未填或格式錯誤</span>
                                </div>
                            @endif
                        </div>
                        <div class="form-group">
                            <label class="col-md-2 control-label" for="form-text-input">分類</label>
                            <div class="col-md-3">
                                <select id="select" class="form-control select2" disabled="disabled">
                                    <option value="">請選擇...</option>
                                    @foreach($specifications as $specification)
                                        <option value="{{ $specification->id }}" @if((isset($item->specification_id) && $item->specification_id == $specification->id) || old('specification_id') == $specification->id){{ 'selected="selected"' }}@endif @if ($specification_id == $specification->id) selected @endif>{{ $specification->name }}</option>
                                    @endforeach
                                    <input type="hidden" name="specification_id" value="{{ $specification_id }}" />
                                    <input type="hidden" name="category_id" value="{{ $category_id }}" />
                                </select>
                            </div>
                            <label class="col-md-2 control-label " for="form-text-input">排序</label>
                            <div class="col-md-2 input-group spinner" data-trigger="spinner">
                                <input name="sort" type="text" class="form-control" value="@if(isset($item->sort)){{ old('sort', $item->sort) }}@else{{ old('sort') }}@endif" data-rule="quantity">
                                <div class="input-group-addon pickers_spinners">
                                    <a href="javascript:;" class="spin-up" data-spin="up"><i class="fa fa-chevron-up"></i></a>
                                    <a href="javascript:;" class="spin-down" data-spin="down"><i class="fa fa-chevron-down"></i></a>
                                </div>
                            </div>
                        </div>
                        <div class="form-group form-actions">
                            <div class="col-md-8 col-md-offset-2">
                                <button type="submit" class="btn btn-effect-ripple btn-primary">送出</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

@section('js')
    <script src="{{ asset('assets/vendors/tinymce/tinymce.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/vendors/ckeditor/js/ckeditor.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/vendors/ckeditor/js/jquery.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/vendors/ckeditor/js/config.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/js/pages/editor1.js') }}" type="text/javascript"></script>

    <script type="text/javascript" src="{{ asset('assets/vendors/iCheck/js/icheck.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/vendors/bootstrap-switch/js/bootstrap-switch.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/vendors/switchery/js/switchery.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/vendors/bootstrap-maxlength/js/bootstrap-maxlength.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/vendors/card/lib/js/jquery.card.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/radio_checkbox.js') }}"></script>
    <script src="{{ asset('assets/vendors/bootstrap-touchspin/js/jquery.bootstrap-touchspin.js') }}"></script>
    <script src="{{ asset('assets/vendors/jquery-spinner/js/jquery.spinner.min.js') }}"></script>
    <script src="{{ asset('assets/js/pages/pickers.js') }}"></script>
    <script>

    </script>
@stop

resources/views/admin/product/specification/item/index.blade.php
@extends('admin.layouts.page')

@section('title', 'Aidlite')

@section('content_header')
    <h1>產品規格項目列表</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('admin.home') }}">
                <i class="livicon" data-name="home" data-size="16" data-color="#000"></i> Dashboard
            </a>
        </li>
        <li>
            <a href="{{ route('admin.product.specifications.list') }}">產品規格分類列表</a>
        </li>
        <li>
            <a href="{{ route('admin.product.specifications.index', ['id' => $category_id]) }}">產品規格列表</a>
        </li>
        <li class="active">
            產品規格項目列表
        </li>
    </ol>
@stop

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-info filterable">
                <div class="panel-heading clearfix">
                    <div class="pull-left">
                        <i class="livicon" data-name="adjust" data-size="18" data-c="white" data-hc="white" data-loop="true"></i>
                    </div>
                    <div class="pull-right">
                        <a href="{{ route('admin.product.specification.items.create', ['id' => $specification_id, 'category_id' => $category_id]) }}" class="btn btn-primary btn-sm">
                            <span><i class="fa fa-plus" id="addButton"></i>&nbsp;&nbsp;新增規格項目</span>
                        </a>
                    </div>
                </div>
                <div class="panel-body table-responsive">
                    <table class="table" id="table3">
                        <thead>
                        <tr>
                            <th>名稱</th>
                            <th>規格</th>
                            <th>排序</th>
                            <th>時間</th>
                            <th>動作</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($items as $item)
                            <tr>
                                <td>{{ $item->name }}</td>
                                <td>
                                    @if (isset($item->specification))
                                        {{ $item->specification->name }}
                                    @endif
                                </td>
                                <td>{{ $item->sort }}</td>
                                <td>{{ $item->updated_at }}</td>
                                <td>
                                    <a href="{{ route('admin.product.specification.items.edit', ['item_id' => $item->id, 'id' => $specification_id, 'category_id' => $category_id]) }}">
                                        <span class="btn btn-success"><i class="fa fa-edit"></i></span>
                                    </a>
                                    <a href="#modal-danger" data-toggle="modal" data-target="#modal-danger" data-variable="{{ route('admin.product.specification.items.destroy', ['id' => $item->id, 'specification_id' => $specification_id, 'category_id' => $category_id]) }}">
                                        <span class="btn btn-danger"><i class="fa fa-trash"></i></span>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            {!! $items->appends(request()->except('page'))->links() !!}
        </div>
    </div>

    <!--window-->
    <div class="modal fade" id="modal-danger" role="document">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-primary">
                    <button type="button" class="close white" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                    <h4><i class="icon fa fa-ban"></i> 提醒</h4>
                </div>
                <div class="modal-body">
                    <p>確定要刪除嗎？</p>
                </div>
                <div class="modal-footer">

                    <form action="" id="delete_form" method="POST">
                        {{ method_field("DELETE") }}
                        {{ csrf_field() }}
                        <button type="button" data-dismiss="modal" class="btn btn-default">取消</button>
                        <input type="submit" class="btn btn-primary" value="確定">
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!--window-->
@stop

@section('js')
    <script>

        $('#modal-danger').on('show.bs.modal', function(e) {
            var $target = $(e.relatedTarget);
            var variable = $target.attr('data-variable');
            console.log(variable);
            $('#delete_form').attr('action', variable);
//            var $modal = $(this);
//            var esseyId = e.relatedTarget.id;
//            $modal.find('.modal-body').html(esseyId);
        })

    </script>
@stop